### ISSUE TITLE
why k8s deployment  Liveness probe failed?

### ISSUE THREAD

**Issue by charlie-charlie** [vernemq/docker-vernemq#137]
Hi there,

After running helm install, my pods in crashloop, here is the issue:
  Normal   Created                 11m (x2 over 14m)  kubelet, ip-10-0-5-93.us-west-2.compute.internal  Created container
  Normal   Started                 11m (x2 over 14m)  kubelet, ip-10-0-5-93.us-west-2.compute.internal  Started container
  Normal   Killing                 11m                kubelet, ip-10-0-5-93.us-west-2.compute.internal  Killing container with id docker://vernemq:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy               9m (x4 over 12m)   kubelet, ip-10-0-5-93.us-west-2.compute.internal  Liveness probe failed: Node 'VerneMQ@vernemq-1..vernemq.svc.cluster.local' not responding to pings.
  Warning  Unhealthy               3m (x28 over 12m)  kubelet, ip-10-0-5-93.us-west-2.compute.internal  Readiness probe failed: Node 'VerneMQ@vernemq-1..vernemq.svc.cluster.local' not responding to pings.

When looking at the pod name, headless service name missing. Have anyone tried to fix it and get the cluster working?

Thanks

**Comment by charlie-charlie** [comment]
I tried 1.7.1 and 1.8.0 2 version on k8s. Both of them failed livenessprobe

**Comment by deepaksood619** [comment]
If i am setting `DOCKER_VERNEMQ_DISCOVERY_KUBERNETES` environment variable then probes failed. Removing this environment pod starts perfectly.
```
- name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
   value: "1"
```

Also the envs
```
- name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
              value: "1"
            - name: DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR
              value: "app.kubernetes.io/name=vernemq,app.kubernetes.io/instance=ve"
```
are not getting inside container as shown in `describe` pod. Its shown in `helm get <release_name>` but never get into `describe` command.
Due to this auto discovery is not working in helm chart.

I have used `appVersion: 1.8.0` and chart `version: 1.3.0`, got using `helm inspect vernemq/vernemq`
