### ISSUE TITLE
Default VerneMQ config is not being replaced via Dockerfile

### ISSUE THREAD

**Issue by dirtybits** [vernemq/docker-vernemq#144]
I'm attempting to overwrite the default config with my own using the following commands in my Dockerfile, but the default configs remain:
```
COPY vernemq.conf.local /vernemq/etc/vernemq.conf
COPY vernemq.conf.local /etc/vernemq/vernemq.conf
```
I also tried:
```
COPY vernemq.conf /vernemq/etc/vernemq.conf.local
COPY vernemq.conf /etc/vernemq/vernemq.conf.local
```
to no avail

**Comment by dergraf** [comment]
Thanks for opening the issue. Can you check with `docker exec <containerid> cat /vernemq/etc/vernemq.conf.local` whether the container can find your config?

**Comment by dirtybits** [comment]
getting `No such file or directory`

**Comment by dergraf** [comment]
Well then the file hasn't been properly copied to the image. Can you paste the adjusted Dockerfile as well as the command you use to buiild the image?

**Comment by dirtybits** [comment]
I tried the 4 combinations of COPY shown below in the CONFIG COPY section of the Dockerfile, all with the same result: `No such file or directory`.
The commands I run are: 
```
docker build -t vernemq .
docker-compose up
```
Dockerfile
```
FROM erlio/docker-vernemq:latest

ENV DOCKER_VERNEMQ_LOG__CONSOLE=console \
    DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on \
    DOCKER_VERNEMQ_listener.tcp.default=172.17.0.2:1883

# # The following copying doesn't work, so we'll use ENV instead:
# # https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh#L56-L88

#################   CONFIG COPY   ####################
# COPY vernemq.conf.local /vernemq/etc/vernemq.conf 
# COPY vernemq.conf.local /etc/vernemq/vernemq.conf

# COPY vernemq.conf.local /vernemq/etc/vernemq.conf.local 
# COPY vernemq.conf.local /etc/vernemq/vernemq.conf.local

COPY vernemq.conf /vernemq/etc/vernemq.conf.local 
COPY vernemq.conf /etc/vernemq/vernemq.conf.local

# COPY vernemq.conf /vernemq/etc/vernemq.conf 
# COPY vernemq.conf /etc/vernemq/vernemq.conf
###################################################

EXPOSE 1883/tcp \
       1884/tcp \
       2003
# EXPOSE 8884/tcp

RUN /bin/bash 
```
docker-compose.yml
```
version: "3.3"
services:
  vernemq:
    image: vernemq
    ports:
       - "1883:1883"
      #  - "8884:8884"
      #  - "2003:2003"
       - "8888:8888"
    environment:
      BACKENDS: "webapp"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"
```

Thank you
