### ISSUE TITLE
Errors with Docker Swarm Cluster

### ISSUE THREAD

**Issue by webfrank** [vernemq/docker-vernemq#156]
Hi,
  I just followed the example but although the cluster is UP, the replica nodes connects correctly to the bootstrap node, I got this errors:

[warning] can't connect to cluster node 'VerneMQ@10.0.30.4' due to timeout

for every replica node trying to connect to other replica nodes.

Here is my docker-compose:

`version: "3.7"
  
services:
  vmq0:
    image: erlio/docker-vernemq
    environment:
      DOCKER_VERNEMQ_SWARM: 1
  vmq:
    image: erlio/docker-vernemq
    depends_on:
      - vmq0
    deploy:
      replicas: 3
    ports:
      - "11883:1883"
      - "18888:8888"
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"`

**Comment by larshesel** [comment]
Sounds like a networking/firewall issue and the cluster nodes are not able to establish connections between each other. Can you check if that's the case and perhaps try allowing everything between all cluster nodes just to see if that changes things.

Hope this helps.

**Comment by webfrank** [comment]
Hi, all the three nodes are in the same LAN with all opened ports, is just a test lab. It seems the replica nodes listens on the wrong interface.

**Comment by larshesel** [comment]
Ah, ok - then you probably need to specify on which interface to use. You can set the ip with `DOCKER_IP_ADDRESS`, I believe.

**Comment by webfrank** [comment]
But I'm inside swarm and ip are dynamic

**Comment by larshesel** [comment]
Right, you can also set the interface using `DOCKER_NET_INTERFACE`. See also https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh#L3

**Comment by webfrank** [comment]
It worked with this copose:

`
version: "3.7"

services:
  vmq0:
    image: vernemq/vernemq:1.9.1-alpine
    environment:
      DOCKER_VERNEMQ_SWARM: 1
  vmq:
    image: vernemq/vernemq:1.9.1-alpine
    depends_on:
      - vmq0
    deploy:
      replicas: 3
    ports:
      - "11883:1883"
      - "18888:8888"
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_NET_INTERFACE: eth1
`

**Comment by larshesel** [comment]
Great!

**Comment by iamgbsmith** [comment]
@webfrank Thanks! I had been trying to deploy a Vernemq cluster running in Docker Swarm using a custom overlay network with little success. The inclusion of the DOCKER_NET_INTERFACE: eth1 environment parameter was the missing piece of the puzzle.

**Comment by Qanah** [comment]
@webfrank Thanks! , but still, I have an issue 

```
my-vernemq-stack_vmq.2.r8sdetcwsx86@worker1    | 16:38:19.736 [info] successfully connected to cluster node 'VerneMQ@10.0.45.6'
my-vernemq-stack_vmq.2.r8sdetcwsx86@worker1    | 16:38:29.599 [warning] can't connect to cluster node 'VerneMQ@10.0.45.3' due to timeout
my-vernemq-stack_vmq.2.r8sdetcwsx86@worker1    | 16:38:40.604 [warning] can't connect to cluster node 'VerneMQ@10.0.45.3' due to timeout
my-vernemq-stack_vmq.2.r8sdetcwsx86@worker1    | 16:38:51.607 [warning] can't connect to cluster node 'VerneMQ@10.0.45.3' due to timeout
my-vernemq-stack_vmq.2.r8sdetcwsx86@worker1    | 16:39:02.609 [warning] can't connect to cluster node 'VerneMQ@10.0.45.3' due to timeout
my-vernemq-stack_vmq.2.r8sdetcwsx86@worker1    | 16:39:13.612 [warning] can't connect to cluster node 'VerneMQ@10.0.45.3' due to timeout
```

**Comment by Qanah** [comment]
it is working now with 

```
version: "3.7"
services:
  vmq0:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_USER_QANAH: "password"
      DOCKER_NET_INTERFACE: eth0
  vmq:
    image: vernemq/vernemq
    depends_on:
      - vmq0
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_USER_QANAH: "password"
      DOCKER_NET_INTERFACE: eth1
    ports:
      - 18883:1883
      - 8888:8080
    deploy:
      replicas: 2
```
