### ISSUE TITLE
DOCKER_VERNEMQ_DISCOVERY_KUBERNETES=1 results in startup errors

### ISSUE THREAD

**Issue by matthastie** [vernemq/docker-vernemq#159]
We experience these two errors when we start VerneMQ:

```
2019-09-10T17:34:38.242986488Z /usr/sbin/start_vernemq: line 53: [: too many arguments
2019-09-10T17:34:38.244039701Z sed: -e expression #1, char 56: unknown option to `s'
```

This appears to be a result of recent commits to the following lines of `vernemq.sh`.

```
52: VERNEMQ_KUBERNETES_SUBDOMAIN=${DOCKER_VERNEMQ_KUBERNETES_SUBDOMAIN:-(curl -X GET $insecure --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc.$DOCKER_VERNEMQ_KUBERNETES_CLUSTER_NAME/api/v1/namespaces/$DOCKER_VERNEMQ_KUBERNETES_NAMESPACE/pods?labelSelector=$DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" | jq '.items[0].spec.subdomain' | sed 's/"//g' | tr '\n' '\0')}
53: if [ $VERNEMQ_KUBERNETES_SUBDOMAIN == "null" ]; then
54: VERNEMQ_KUBERNETES_HOSTNAME=${MY_POD_NAME}.${DOCKER_VERNEMQ_KUBERNETES_NAMESPACE}.svc.${DOCKER_VERNEMQ_KUBERNETES_CLUSTER_NAME}
55: else
56: VERNEMQ_KUBERNETES_HOSTNAME=${MY_POD_NAME}.${VERNEMQ_KUBERNETES_SUBDOMAIN}.${DOCKER_VERNEMQ_KUBERNETES_NAMESPACE}.svc.${DOCKER_VERNEMQ_KUBERNETES_CLUSTER_NAME}
    fi
```

We suspect that the curl stats emitted from line 52 might be including space characters in the output, which causes line 53 to fail, due to missing quotes around the dereference of the lhs. If it is indeed the stats that are problematic, adding -s (silent) to curl can give a hostname output, but we conjecture that even if this were to be corrected, the generated hostname (with subdomain calculated) would not be correct for our environment. We request that you please resurrect commit 4c78483 to provide users an option to explicitly configure the subdomain value.

```
echo $(curl -q -X GET --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc.cluster.local/api/v1/namespaces/mqtt/pods?labelSelector=app=vernemq -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" | jq '.items[].spec.hostname' | sed -e 's/"//g' | tr '\n' ' ')
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16242    0 16242    0     0   229k      0 --:--:-- --:--:-- --:--:--  229k
vernemq-0
echo $(curl -s -X GET --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://kubernetes.default.svc.cluster.local/api/v1/namespaces/mqtt/pods?labelSelector=app=vernemq -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" | jq '.items[].spec.hostname' | sed -e 's/"//g' | tr '\n' ' ')
vernemq-0
$ 
```

The output above should demonstrate that our default service account has adequate privileges, and our environment is presented below for completeness:

```
        image: erlio/docker-vernemq:1.9.2
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
          value: "off"
        - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
          value: "1"
        - name: DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR
          value: app=vernemq
```
