### ISSUE TITLE
high idle cpu usage with helm chart due to liveness/readiness probe

### ISSUE THREAD

**Issue by brokenjacobs** [vernemq/docker-vernemq#165]
I've been noticing very high idle cpu usage with the helm chart install in my setup. Over an entire core of cpu usage at idle. Removing the readiness checks reduces this down to less that 10% of one core. It seems it is related to a similar issue with erlang the rabbitMQ folks have experienced here:
https://github.com/GoogleCloudPlatform/click-to-deploy/issues/522 (and lots of similar issues in the rabbitmq isssue tracker)

I would suggest converting the readiness and liveness probes in the helm chart to use an http check against the vernemq health endpoint to fix this.

**Comment by larshesel** [comment]
Thanks for the report - we'll look into it.

**Comment by brokenjacobs** [comment]
I use the following:
```yaml
         livenessProbe:
            httpGet:
              path: /health
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
```
