### ISSUE TITLE
How to use secretMounts for passwd and acl in k8s?

### ISSUE THREAD

**Issue by donfmorrison** [vernemq/docker-vernemq#168]
I probably doing it wrong, but I'm having trouble using the new `secretMounts` settings with the helm chart. Here is my secrets file which I converted the contents of both my `passwd` and `acl` file to base64:

```
apiVersion: v1
kind: Secret
metadata:
  name: vernemq-secrets
  namespace: vernemq
data:
  vmq.passwd: #{vmq-passwd}#
  vmq.acl: #{vmq-acl}#
type: Opaque
```

... and my values.yaml:

```
...
persistentVolume:
  ## If true, VerneMQ will create/use a Persistent Volume Claim
  ## If false, use local directory
  enabled: false

  ...
  # A list of secrets and their paths to mount inside the pod
  # This is useful for mounting certificates for security (tls)
  secretMounts:
    - name: vernemq-secrets
      secretName: vernemq-secrets
      path: /etc/vernemq
...
```

I'm sure I'm doing it wrong, but my goal is to have the secrets for both `acl` and `passwd` mount and be used by the cluster.

**Comment by dergraf** [comment]
@donfmorrison can you share more information about what isn't working? E.g. some logs. If possible try to do an `ls -la /etc/vernemq` just to confirm that the files are there (or not) and have the proper permissions.

**Comment by donfmorrison** [comment]
@dergraf Looks like those secrets aren't being mounted:
```powershell
kubectl exec vernemq-0 --namespace vernemq -- ls -la /etc/vernemq
lrwxrwxrwx    1 root     root            12 Sep 27 06:19 /etc/vernemq -> /vernemq/etc
```
```powershell
kubectl exec vernemq-0 --namespace vernemq -- ls -la /vernemq/etc
total 60
drwxr-xr-x    2 vernemq  vernemq       4096 Oct 23 04:51 .
drwxr-xr-x    1 vernemq  vernemq       4096 Oct 23 04:51 ..
-rw-r--r--    1 vernemq  vernemq      38877 Oct 23 04:51 vernemq.conf
-rw-r--r--    1 vernemq  vernemq        352 Oct 23 04:51 vm.args
-rw-r--r--    1 vernemq  vernemq        217 Oct 23 04:51 vm.args.bak
-rw-r--r--    1 vernemq  vernemq          8 Sep 27 06:08 vmq.acl
```
Secrets do appear to be present:
```powershell
kubectl describe secrets/vernemq-secrets --namespace vernemq
Name:         vernemq-secrets
Namespace:    vernemq
Labels:       <none>
Annotations:
Type:         Opaque

Data
====
vmq.acl:     506 bytes
vmq.passwd:  947 bytes
```
Are there specific logs that would help?

**Comment by dergraf** [comment]
Something comes to mind that I learned just recently. In the Dockerfile we declare a `/vernemq/etc` as a volume (see https://github.com/vernemq/docker-vernemq/blob/master/Dockerfile#L58), at this point I am not sure if this is the wisest thing to do (@drf, @francois-travais, @codeadict).

As a consequence a volume gets automatically created and survives the deletion of the container. BUT (if I understand it correctly) when the container gets restarted it uses the existing volume automatically and doesn't mount a 'new' volume that may contain new data. Do you think it is possible that this could causing this issue here?

**Comment by drf** [comment]
@dergraf - about the volume, I agree it might not the best approach, although it is unlikely to cause that issue you mentioned. Also, removing it would alter a well-known behavior for current users so I'd be extremely reluctant in doing so - it needs proper messaging and an upgrade path.

The first thing that comes to my mind is that, if @donfmorrison pasted his yaml correctly, secretMounts is in the wrong hierarchy (under persistentVolume instead of being top-level), and this basically doesn't make it work.

**Comment by donfmorrison** [comment]
@drf good catch! I did have the `secretMounts` section at the wrong level underneath `persistentVolume`. FIxed that.

Deployments failed using mount path `/etc/vernemq` so there might be something to your thoughts there. Changing to different mount path resolved all issues.

Secret files mount and setting the path to passwd and acl files via config variables get's everything working as expected. 
```yaml
secretMounts:
  - name: vernemq-auth
    secretName: vernemq-secrets
    path: /vernemq/auth
```

Thank you!
