### ISSUE TITLE
Helm chart or docker tag incorrect

### ISSUE THREAD

**Issue by richardprior** [vernemq/docker-vernemq#175]
Chart specifies:

```yaml
image:
  repository: vernemq/vernemq
  tag: 1.10.0-alpine
```

Docker hub does not contain that tag, appears to be published as ```alpine-1.10.0```
