### ISSUE TITLE
ACL using environment variables

### ISSUE THREAD

**Issue by dannyyy** [vernemq/docker-vernemq#183]
In the `README.md` is noted that new users can be created through environment variables in the form of `DOCKER_VERNEMQ_USER_<USERNAME>='password'`.

Is there a similar way to define the ACLs for the created users through environment variables?

I guess I can create a secret to mount the `vmq.passwd` and `vmq.acl` and change the path to these files with `DOCKER_VERNEMQ_VMQ_PASSWD__PASSWORD_FILE` and ´DOCKER_VERNEMQ_VMQ_ACL__.ACL_FILE´.  But an easier way would be preferable over managing different files.

**Comment by mladen-djordjevic** [comment]
@dannyyy , did you manage to set ACL rules via environment variables or some other way?

**Comment by masantiago** [comment]
I managed to do it by creating a configmap containing the vmq.acl file like

```
apiVersion: v1
kind: ConfigMap
metadata:  
  name: vernemq-acl
  labels:
{{ include "labels" . | indent 4}}    
data:  
  vernemq-acl: |-  
{{ .Files.Get .Values.vernemq.acl | indent 4 }}
```
and, later, referencing it on values.yaml with the extra volume options:
```
extraVolumeMounts:
    - name: vernemq-acl
      mountPath: /vernemq/etc/vmq.acl
      subPath: vernemq-acl 
      readOnly: true  
extraVolumes:
    - name: vernemq-acl
      configMap:
        name: vernemq-acl
```
