### ISSUE TITLE
cluster in docker swarm does not work 

### ISSUE THREAD

**Issue by KonstantinNosov** [vernemq/docker-vernemq#187]
using sample from documentation 
```
version: "3.7"
services:
  vmq0:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_SWARM: 1
  vmq:
    image: vernemq/vernemq
    depends_on:
      - vmq0
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
    deploy:
      replicas: 2
```

vmq fails to connect to the cluster 
```
19:06:42.774 [info] Sent join request to: 'VerneMQ@23.217.138.108'
19:06:42.963 [info] Unable to connect to 'VerneMQ@23.217.138.108'
```
I see 2 issues with the sample.:
1. in Compose file version 3 reference it is stated that `The depends_on option is ignored when deploying a stack in swarm mode with a version 3 Compose file.` 
2. vernemq.sh waits for `getent hosts tasks.$discovery_node` to return at least 1 IP and uses it to connect to cluster while it looks like in swarm mode `getent hosts tasks.[unknown name]`  is always resolved to a pair of IPs:
```
 docker exec 949f3ae1aacf getent hosts tasks.whatever_is_here_it_is_resolvable
23.217.138.108  tasks.whatever_is_here_it_is_resolvable
23.202.231.167  tasks.whatever_is_here_it_is_resolvable
```

Sorry if I'm missing something obvious, I'm new to docker. Will appreciate any hint on how to setup VMQ on Docker Swarm.
