### ISSUE TITLE
Failed to open log file ./log/error.log. Permission denided.

### ISSUE THREAD

**Issue by alishir** [vernemq/docker-vernemq#201]
Hi all,

I tried to test vernemq docker image with docker-compose, but I get permission denied error when using external directory for log files. Here is the `docker-compole.yml` file:

```yml
version: '2'
services:
  vernemq:
    image: vernemq/vernemq:1.10.2-1
    ports:
      - "1883:1883"
      - "8008:8080"
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
    volumes:
      - ./vernemq/log/:/vernemq/log/
```
