### ISSUE TITLE
Prometheus doesn't scrape the /metrics

### ISSUE THREAD

**Issue by rolfberkenbosch** [vernemq/docker-vernemq#206]
Hi All,

Prometheus doesn't scrape the config from vernemq, i have the following helm config:

```yaml
          image:
            repository: vernemq/vernemq
            tag: 1.10.2-1-alpine
          replicaCount: 1
          serviceMonitor:
            create: true
            enabled: true
          service:
            loadBalancerIP: 192.168.1.200
            type: LoadBalancer
            ws:
              enabled: true
          nodeSelector:
            kubernetes.io/arch: amd64
          persistentVolume:
            enabled: true
            size: 10Gi
            storageClass: "nfs-client"
          ingress:
            enabled: true
            host:
              - vernemq.marrol.nl
            annotations: 
              kubernetes.io/ingress.class: traefik
          statefulset:
            podAnnotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8888"
          additionalEnv:
            - name: DOCKER_VERNEMQ_ACCEPT_EULA
              value: "yes"
            - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
              value: "on"
```

```bash
kubectl get all -n ha
NAME                                        READY   STATUS    RESTARTS   AGE
pod/vernemq-0                               1/1     Running   0          20m
pod/svclb-vernemq-rh2dx                     2/2     Running   0          6m15s
pod/svclb-vernemq-7kqzq                     2/2     Running   0          3m35s
pod/svclb-vernemq-z5ht2                     2/2     Running   0          3m25s
pod/svclb-vernemq-8zk45                     2/2     Running   0          3m10s

NAME                           TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                         AGE
service/vernemq-headless       ClusterIP      None            <none>          4369/TCP,8888/TCP               70m
service/vernemq                LoadBalancer   10.43.52.31     192.168.1.203   1883:30162/TCP,8080:31046/TCP   70m

NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/svclb-vernemq   4         4         4       4            4           <none>          70m

NAME                       READY   AGE
statefulset.apps/vernemq   1/1     70m
```

It looks like that everything is running. I'm wondering is the headless service doesn't have an ClusterIP. Is that not needed for prometheus for scraping the /metrics ?
