### ISSUE TITLE
Helm: ServiceMonitor for Prometheus Operator

### ISSUE THREAD

**Issue by onedr0p** [vernemq/docker-vernemq#228]
Prometheus Operator has a `ServiceMonitor` CRD that allows you to put the scrape configs in that resource so we don't need to add the config manually to Prometheus.

Here's an example I just pulled up:

```yaml
prometheus:
  enabled: false
  serviceMonitor:
    # Enables ServiceMonitor creation for the Prometheus Operator
    create: false
    interval:
    scrapeTimeout:
    namespace:
    additionalLabels: {}
```

And the ServiceMonitor manifest looks something like this:

https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/templates/servicemonitor.yaml

Would this be something you'd be willing to support? If so, I can open a PR for review.
Thanks!

This is related to https://github.com/vernemq/docker-vernemq/issues/206
