### ISSUE TITLE
Docker Swarm Error: Connection refused

### ISSUE THREAD

**Issue by Qanah** [vernemq/docker-vernemq#240]
finally, I reach a stable connection with this stack, my issue is docker working with net interface eth0 and the cluster work on eth1 now how can i export the ports if i use 1883:1883 and try ro run this mosquitto_sub i see Error: Connection refused

mosquitto_sub -h 192.168.99.113 -p 1883 -i client-id -u qanah -P password -t '#'

please i need help if i change the DOCKER_NET_INTERFACE the cluster will not connect 

```
version: "3.7"
services:

  vmq0:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_USER_QANAH: "password"
      DOCKER_NET_INTERFACE: eth0
    networks:
      - vmq_net

  vmq:
    depends_on:
      - vmq0
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_USER_QANAH: "password"
      DOCKER_NET_INTERFACE: eth1
    networks:
      - vmq_net
    ports:
      - 1883:1883
      - 8080:8080
    deploy:
      replicas: 2

networks:
  vmq_net:
    driver: overlay
```

docker service ls

```
ID                  NAME                MODE                REPLICAS            IMAGE                    PORTS
dxkdtkfckrl4        vernemq_vmq         replicated          2/2                 vernemq/vernemq:latest   *:1883->1883/tcp, *:8080->8080/tcp
ygilci9pi3yz        vernemq_vmq0        replicated          1/1                 vernemq/vernemq:latest 
```

docker service logs vernemq_vmq

```
vernemq_vmq.2.hxuxpnqgfufu@manager1    | 11:33:52.345 [info] successfully connected to cluster node 'VerneMQ@10.0.27.40'
vernemq_vmq.2.hxuxpnqgfufu@manager1    | 11:33:53.031 [info] successfully connected to cluster node 'VerneMQ@10.0.27.36'
```

docker service logs vernemq_vmq0

```
vernemq_vmq0.1.rf7x319hrb2h@worker1    | 11:33:52.330 [info] successfully connected to cluster node 'VerneMQ@10.0.27.37'
vernemq_vmq0.1.rf7x319hrb2h@worker1    | 11:33:53.015 [info] successfully connected to cluster node 'VerneMQ@10.0.27.36'
```

docker exec a8c682052bf9 vmq-admin cluster show

```
+--------------------+---------+
| Node               | Running |
+--------------------+---------+
| VerneMQ@10.0.27.40 | true    |
+--------------------+---------+
| VerneMQ@10.0.27.36 | true    |
+--------------------+---------+
| VerneMQ@10.0.27.37 | true    |
+--------------------+---------+
```

**Comment by Qanah** [comment]
finally, this is my solution

```
version: "3.7"
services:
  vmq0:
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_NET_INTERFACE: eth0
      DOCKER_VERNEMQ_USER_QANAH: 'password'
    networks:
      - vmq_net
    command: >
      /bin/sh -c "cp /usr/sbin/start_vernemq /vernemq/etc/start_vernemq &&
      sed -i 's/listener.tcp.default.*:1883/listener.tcp.default = 0.0.0.0:1883/g' /vernemq/etc/start_vernemq &&
      sed -i 's/listener.ws.default.*:8080/listener.ws.default = 0.0.0.0:8080/g' /vernemq/etc/start_vernemq &&
      sed -i 's/listener.http.metrics.*:8888/listener.http.metrics = 0.0.0.0:8888/g' /vernemq/etc/start_vernemq &&
      chmod +x /vernemq/etc/start_vernemq &&
      /vernemq/etc/start_vernemq &&
      rm -rf /vernemq/etc/start_vernemq"

  vmq:
    depends_on:
      - vmq0
    image: vernemq/vernemq
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_NET_INTERFACE: eth1
      DOCKER_VERNEMQ_USER_QANAH: 'password'
    networks:
      - vmq_net
    ports:
      - 1883:1883
      - 8080:8080
    command: >
      /bin/sh -c "cp /usr/sbin/start_vernemq /vernemq/etc/start_vernemq &&
      sed -i 's/listener.tcp.default.*:1883/listener.tcp.default = 0.0.0.0:1883/g' /vernemq/etc/start_vernemq &&
      sed -i 's/listener.ws.default.*:8080/listener.ws.default = 0.0.0.0:8080/g' /vernemq/etc/start_vernemq &&
      sed -i 's/listener.http.metrics.*:8888/listener.http.metrics = 0.0.0.0:8888/g' /vernemq/etc/start_vernemq &&
      chmod +x /vernemq/etc/start_vernemq &&
      /vernemq/etc/start_vernemq &&
      rm -rf /vernemq/etc/start_vernemq"
    deploy:
      replicas: 2

networks:
  vmq_net:
    driver: overlay
```
