### ISSUE TITLE
TLS termination on AWS LB prevents successful connection

### ISSUE THREAD

**Issue by edmeister** [vernemq/docker-vernemq#241]
Hi,

We deployed the latest version of the Helm chart (1.6.5) onto our Kubernetes clusters running on AWS (1.18) and chose to add a public load balancer in front of the VerneMQ pods. According to the documentation, we added our TLS certificates on the load balancer. However, we don't succeed in connecting to the VerneMQ brokers.  

When we remove the TLS from the NLB or ELB, everything works as expected. With a port-forward directly to the pod or the service, everything runs perfectly too.

We tried with both the Elastic/Classic and the Network load balancer, btw. Results were the same.

Does anybody have any idea what we might be doing wrong? Is there a reference configuration for a setup on AWS?

A snippet from our helm values, all very straight-forward:

```
service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${hostName}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${certificateArn}
```
