### ISSUE TITLE
Errors in docker swarm cluster with custom overlay network

### ISSUE THREAD

**Issue by jjaimon** [vernemq/docker-vernemq#252]
I'm trying to get a cluster running on my swarm cluster where I've a custom defined overlay network. 

here is my compose file
```
services:
  vmq0:
    image: vernemq/vernemq
    environment:
      - "DOCKER_VERNEMQ_SWARM=1"
      - "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
      - "DOCKER_VERNEMQ_LISTENER__VMQ__CLUSTERING=0.0.0.0:44053"
    networks:
        - default

  vmq:
    image: vernemq/vernemq
    depends_on:
      - vmq0
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18888:18888"
    environment:
      - "DOCKER_VERNEMQ_SWARM=1"
      - "DOCKER_VERNEMQ_DISCOVERY_NODE=vmq0"
      - "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on"
      - "DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES=0"
      - "DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES=-1"
      - "DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES=-1"
      - "DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT=0.0.0.0:1883"
      - "DOCKER_VERNEMQ_LISTENER__WS__DEFAULT=0.0.0.0:8083"
      - "DOCKER_VERNEMQ_LISTENER__HTTP__DEFAULT=0.0.0.0:18888"
      - "DOCKER_VERNEMQ_LOG__CONSOLE=console"
      - "DOCKER_VERNEMQ_SHARED_SUBSCRIPTION_POLICY=random"
      - "DOCKER_VERNEMQ_ACCEPT_EULA=yes"
      - "DOCKER_VERNEMQ_LISTENER__VMQ__CLUSTERING=0.0.0.0:44053"
    deploy:
      mode: replicated
      replicas: 1
    networks:
        - default

networks:
  default:
    external: true
    name: overlaynet
```
Nodes were not able to discover each other unless I set `DOCKER_VERNEMQ_LISTENER__VMQ__CLUSTERING`.

I can see following interfaces in vmq0. 172.20.0.x is the custom overlaynet I created for all our services.
```
eth0: inet 172.20.0.139
eth1: inet 172.18.0.19
lo: inet 172.0.0.1
```
and cluster query shows the following
```
+----------------------+---------+
| Node                 | Running |
+----------------------+---------+
| VerneMQ@172.20.0.137 | true    |
+----------------------+---------+
| VerneMQ@172.20.0.139 | true    |
+----------------------+---------+
```

Following interfaces are available on vmq
```
eth0: inet 10.0.0.68
eth1: inet 172.20.0.137
eth2: inet 172.18.0.17
lo: inet 127.0.0.1
```
and cluster query shows:
```
+----------------------+---------+
| Node                 | Running |
+----------------------+---------+
| VerneMQ@172.20.0.137 | true    |
+----------------------+---------+
| VerneMQ@172.20.0.139 | true    |
+----------------------+---------+
```
So, it all looks okay.  However, both nodes keeps printing the following warning every second
vmq0:
```
18:23:40.367 [info] successfully connected to cluster node 'VerneMQ@172.20.0.137'
18:23:40.367 [warning] terminate due to remote_node_not_available
18:23:40.367 [warning] connection to node 'VerneMQ@172.20.0.137' has been closed, reconnect in 1000ms
```
vmq:
```
18:24:20.448 [info] successfully connected to cluster node 'VerneMQ@172.20.0.139'
18:24:20.448 [warning] terminate due to remote_node_not_available
18:24:20.448 [warning] connection to node 'VerneMQ@172.20.0.139' has been closed, reconnect in 1000ms
```
Why am I seeing above warning?  How do I address this?  How do I validate the cluster is joined correctly?
