### ISSUE TITLE
VerneMQ Swarm recovery delay

### ISSUE THREAD

**Issue by molestinsky** [vernemq/docker-vernemq#271]
Hi all,
we deployed VerneMQ swarm cluster according to the official documentation. Everything goes ok until any node falls.
If it happens all connections freeze for ~1 minute (pub and sub) and then works normally. 
There are no freezes if node comes up.
What makes such long delays and is there any way to decrease them? 

Here is my docker-compose.yml:
```
version: "3.7"
services:
  vmq0:
    image: vernemq/vernemq:1.10.4.1
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_LISTENER__MOUNTPOINT: "on"
      DOCKER_VERNEMQ_LISTENER__SSL__MOUNTPOINT: "ssl-mnt"
      DOCKER_VERNEMQ_LISTENER__TCP__MOUNTPOINT: "tcp-mnt"
      DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT: "on"
      DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT: "on"
      DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT: "on"
      DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT: "on"
      DOCKER_VERNEMQ_COORDINATE_REGISTRATIONS: "on"
      DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES: "100"
      DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES: "1000"
      DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES: "1000"
      DOCKER_VERNEMQ_MAX_MESSAGE_SIZE: "0"
      DOCKER_VERNEMQ_UPGRADE_OUTGOING_QOS: "on"
      DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS: "10000"
      DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS: "100"
      DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT: "0.0.0.0:1883"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: "0.0.0.0:8883"
      #DOCKER_VERNEMQ_LISTENER__VMQ__CLUSTERING: "0.0.0.0:44053"
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: "/etc/vernemq/ssl/all-sbrf-CA.pem"
      DOCKER_VERNEMQ_LISTENER__SSL__DEPTH: "1"
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: "/etc/vernemq/ssl/signed-server.pem"
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: "/etc/vernemq/ssl/sbrf-server.key"
      DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE: "off"
      DOCKER_VERNEMQ_LISTENER__SSL__USE_IDENTITY_AS_USERNAME: "off"
      DOCKER_VERNEMQ_SYSTREE_ENABLED: "on"
      DOCKER_VERNEMQ_SYSTREE_INTERVAL: "20000"
      DOCKER_VERNEMQ_SHARED_SUBSCRIPTION_POLICY: "prefer_local"
      DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
      DOCKER_VERNEMQ_LISTENER__SSL__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
      DOCKER_VERNEMQ_LISTENER__WS__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
      DOCKER_VERNEMQ_LISTENER__WSS__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
      DOCKER_NET_INTERFACE: "eth1"
    volumes:
      - ./vernemq/vmq.acl:/etc/vernemq/vmq.acl
      - ./vernemq/vmq.passwd:/etc/vernemq/vmq.passwd
      - ./vernemq/ssl/:/etc/vernemq/ssl/
    networks:
      - main
      
  vmq:
    image: vernemq/vernemq:1.10.4.1
    depends_on:
      - vmq0
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes" 
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_DISCOVERY_NODE: vmq0
      DOCKER_VERNEMQ_LISTENER__MOUNTPOINT: "on"
      DOCKER_VERNEMQ_LISTENER__SSL__MOUNTPOINT: "ssl-mnt"
      DOCKER_VERNEMQ_LISTENER__TCP__MOUNTPOINT: "tcp-mnt"
      DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT: "on"
      DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT: "on"
      DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT: "on"
      DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT: "on"
      DOCKER_VERNEMQ_COORDINATE_REGISTRATIONS: "on"
      DOCKER_VERNEMQ_MAX_INFLIGHT_MESSAGES: "100"
      DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES: "1000"
      DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES: "1000"
      DOCKER_VERNEMQ_MAX_MESSAGE_SIZE: "0"
      DOCKER_VERNEMQ_UPGRADE_OUTGOING_QOS: "on"
      DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS: "10000"
      DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS: "100"
      DOCKER_VERNEMQ_LISTENER__TCP__DEFAULT: "0.0.0.0:1883"
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: "0.0.0.0:8883"
      #DOCKER_VERNEMQ_LISTENER__VMQ__CLUSTERING: "0.0.0.0:44053"
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: "/etc/vernemq/ssl/all-sbrf-CA.pem"
      DOCKER_VERNEMQ_LISTENER__SSL__DEPTH: "1"
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: "/etc/vernemq/ssl/signed-server.pem"
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: "/etc/vernemq/ssl/sbrf-server.key"
      DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE: "off"
      DOCKER_VERNEMQ_LISTENER__SSL__USE_IDENTITY_AS_USERNAME: "off"
      DOCKER_VERNEMQ_SYSTREE_ENABLED: "on"
      DOCKER_VERNEMQ_SYSTREE_INTERVAL: "20000"
      DOCKER_VERNEMQ_SHARED_SUBSCRIPTION_POLICY: "prefer_local"
      DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
      DOCKER_VERNEMQ_LISTENER__SSL__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
      DOCKER_VERNEMQ_LISTENER__WS__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
      DOCKER_VERNEMQ_LISTENER__WSS__ALLOWED_PROTOCOL_VERSIONS: "3,4,5"
      DOCKER_NET_INTERFACE: "eth1"
    ports:
       - target: 8883
         published: 8883
       - target: 1883
         published: 1883
    volumes:
      - ./vernemq/vmq.acl:/etc/vernemq/vmq.acl
      - ./vernemq/vmq.passwd:/etc/vernemq/vmq.passwd
      - ./vernemq/ssl/:/etc/vernemq/ssl/
    networks:
      - main
      
    deploy:
        mode: global

networks:
  main:
    driver: overlay
```
