### ISSUE TITLE
Kubernetes Stateful Clustering not working properly

### ISSUE THREAD

**Issue by Robbilie** [vernemq/docker-vernemq#304]
The helm chart sets up a statefulset and while that should guarantee a certain level of stability it apparently isnt enough to properly cluster in all cases. I am currently running two nodes and when i connect with a subscribing client and then start to publish using another i get only 50% of the published messages on the first client. If i kill one of the two nodes using kubectl it seems to fix it, i am unsure if permanently because i dont recall recreating the nodes and right now it happens again but they may have been rescheduled.

To me it seems the nodes dont always properly form a cluster.

**Comment by Robbilie** [comment]
```
rschuh@leonis:~$ kubectl exec -ti -n vernemq vernemq-0 vmq-admin cluster show
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
+--------------------------------------------------------------+---------+
| Node                                                         | Running |
+--------------------------------------------------------------+---------+
| VerneMQ@vernemq-0.vernemq-headless.vernemq.svc.cluster.local | true    |
+--------------------------------------------------------------+---------+
rschuh@leonis:~$ kubectl exec -ti -n vernemq vernemq-1 vmq-admin cluster show
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
+--------------------------------------------------------------+---------+
| Node                                                         | Running |
+--------------------------------------------------------------+---------+
| VerneMQ@vernemq-1.vernemq-headless.vernemq.svc.cluster.local | true    |
+--------------------------------------------------------------+---------+
```

**Comment by Robbilie** [comment]
actually, killing the pods does not work at all right now…

**Comment by Robbilie** [comment]
log output of vernemq-1 says though:

`Will join an existing Kubernetes cluster with discovery node at vernemq-0.vernemq-headless.vernemq.svc.cluster.local`

**Comment by ioolkos** [comment]
@Robbilie It's all happening in the `vernemq.sh` script: https://github.com/vernemq/docker-vernemq/blob/5b2f21c87fa8433892acd5e6a654812d888b0bc6/bin/vernemq.sh#L80

so i guess that's where we have to look/doublecheck.

**Comment by ioolkos** [comment]
I"ll be looking into the Helm stuff within the coming days.

**Comment by Robbilie** [comment]
lovely, if you need any assistance or want me to test something, let me know :)

**Comment by stewiezc** [comment]
I was having the same issue and narrowed it down to the image I was building, so this may not apply if you are using the public image. 
Take a look at the /etc/vernemq/vm.args file in your running container and make sure it looks correct and has the join command in it. I was missing a line break in my base image vm.args file and so the join command was never executing correctly. 

Should look something like this:
```
+P 256000
-env ERL_MAX_ETS_TABLES 256000
-env ERL_CRASH_DUMP /erl_crash.dump
-env ERL_FULLSWEEP_AFTER 0
-env ERL_MAX_PORTS 256000
+A 64
-setcookie vmq
-name VerneMQ@vernemq-0.vernemq-headless.default.svc.cluster.local
+K true
+W w
-smp enable
+zdbbl 32768
-eval "vmq_server_cmd:node_join('VerneMQ@vernemq-1.vernemq-headless.default.svc.cluster.local')"
```

Hope that helps.

**Comment by Robbilie** [comment]
the join command is part of the start script:

https://github.com/vernemq/docker-vernemq/blob/master/bin/vernemq.sh

**Comment by reketen** [comment]
I have the same issue. 2 nodes in the K8s cluster behave as they are separate clusters:

node0:
bash-4.4$ vmq-admin cluster show
+--------------------------------------------------------------------------------------------------+---------+
| Node                                                                                             | Running |
+--------------------------------------------------------------------------------------------------+---------+
| VerneMQ@vernemq-development-0.vernemq-development-headless.vernemq-development.svc.cluster.local | true    |
+--------------------------------------------------------------------------------------------------+---------+

node1:

bash-4.4$ vmq-admin cluster show
+--------------------------------------------------------------------------------------------------+---------+
| Node                                                                                             | Running |
+--------------------------------------------------------------------------------------------------+---------+
| VerneMQ@vernemq-development-1.vernemq-development-headless.vernemq-development.svc.cluster.local | true    |
+--------------------------------------------------------------------------------------------------+---------+

It is very strange because I have the same helm chart with the same values deployed in another namespace and it works fine - I have 2 nodes in the cluster.

Here is values.yaml file: 

```
replicaCount: 2

service:
  type: LoadBalancer
  mqtt:
    enabled: false
  mqtts:
    enabled: true

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

secretMounts:
  - name: tls-config
    secretName: vernemq-certificates-secret
    path: /etc/vernemq/ssl

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi

additionalEnv:
  - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
    value: "on"
  - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
    value: "on"

  # VerneMQ Accept EULA Afrer helm-1.5.0
  - name: DOCKER_VERNEMQ_ACCEPT_EULA
    value: "yes"

  # VerneMQ Log level
  - name: DOCKER_VERNEMQ_LOG__CONSOLE
    value: console
  - name: DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL
    value: info

  # VerneMQ config
  - name: DOCKER_VERNEMQ_LISTENER__MAX_CONNECTIONS
    value: "96000"
  - name: DOCKER_VERNEMQ_LISTENER__NR_OF_ACCEPTORS
    value: "100"
  - name: DOCKER_VERNEMQ_MAX_CLIENT_ID_SIZE
    value: "128"
  - name: DOCKER_VERNEMQ_MAX_MESSAGE_SIZE
    value: "524288"
  - name: DOCKER_VERNEMQ_PERSISTENT_CLIENT_EXPIRATION
    value: "1h"
  - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
    value: "off"
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_ACL
    value: "off"
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD
    value: "off"
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY
    value: "off"
  - name: DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS
    value: "on"

  # TLS config
  - name: DOCKER_VERNEMQ_LISTENER__SSL__CAFILE
    value: "/etc/vernemq/ssl/ca.crt"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE
    value: "/etc/vernemq/ssl/tls.crt"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE
    value: "/etc/vernemq/ssl/tls.key"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT
    value: "0.0.0.0:8883"
  # - name: DOCKER_VERNEMQ_LISTENER__SSL__TLS_VERSION
  #   value: "tlsv1.2"
  # - name: DOCKER_VERNEMQ_LISTENER__SSL__DEPTH
  #   value: "3"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE
    value: "on"
  - name: DOCKER_VERNEMQ_LISTENER__SSL__USE_IDENTITY_AS_USERNAME
    value: "on"
```
In the pod log I see that it was going to join the cluster:

Will join an existing Kubernetes cluster with discovery node at vernemq-development-1.vernemq-development-headless.vernemq-development.svc.cluster.local
config is OK
