### ISSUE TITLE
Need for a better control of the statefulSet updateStrategy

### ISSUE THREAD

**Issue by Thlr** [vernemq/docker-vernemq#400]
The `statefulSet.updateStrategy` value that we are presented with directly sets the `type` field of the updateStrategy in the statefulset manifest:

```yaml
# statefulset.yaml
  updateStrategy:
    type: {{ .Values.statefulset.updateStrategy }}
```

This leaves us no option to configure the `rollingUpdate` field of the manifest (which I need to change) -> [reference for the Kubernetes API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#statefulsetupdatestrategy-v1-apps).

For instance : 

```yaml
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```

This could be achieved by changing the value (breaking change) so that it affects the whole `updateStrategy` field:

```yaml
# statefulset.yaml
  updateStrategy: {{ .Values.statefulset.updateStrategy | nindent 2 }}
```

Or adding an additional value:

```yaml
# values.yaml
updateStrategy: rollingUpdate
rollingUpdate: {}
``` 

```yaml
# statefulset.yaml
  updateStrategy:
    type: {{ .Values.statefulset.updateStrategy }}
    {{- with .Values.statefulset.rollingUpdate }}
    rollingUpdate: {{- toYaml . | nindent 4 }}
    {{- end }}
```

While the first implementation is more idiomatic of the kubernetes api (the value and the api field sharing the same name, it makes sense that they affect the same portion of the manifest), the second option introduces no breaking change.
