### ISSUE TITLE
Clustering shows pods as running but logs are throwing warnings

### ISSUE THREAD

**Issue by KarthikSubramanian2** [vernemq/docker-vernemq#78]
i am trying to deploy vernemq onto K8s. When i deploy the stateful set, the command 
`kubectl exec vernemq-0 -- vmq-admin cluster show` gives me the following ouput,
+-----------------------------------------------+-------+
|                     Node                      |Running|
+-----------------------------------------------+-------+
|VerneMQ@vernemq-0.vernemq.test.svc.cluster.local| true  |
|VerneMQ@vernemq-1.vernemq.test.svc.cluster.local| true  |
+-----------------------------------------------+-------+

When i log into one of the pods and look at the logs, here is what i see,
`2018-11-05 20:21:49.607 [info] <0.420.0>@vmq_cluster_node:connect:244 successfully connected to cluster node 'VerneMQ@vernemq-0.vernemq.test.svc.cluster.local'
2018-11-05 20:21:49.607 [warning] <0.2525.0>@vmq_cluster_com:loop:74 terminate due to remote_node_not_available`

Seems like it has conflicting output. I can't connect to the nodes though. 

Here is my config.

```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: vernemq
  namespace: test
spec:
  serviceName: vernemq
  replicas: 2
  selector:
    matchLabels:
      app: vernemq
  template:
    metadata:
      labels:
        app: vernemq
    spec:
      containers:
      - name: vernemq
        image: erlio/docker-vernemq:1.3.1
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 8883
          name: mqtts
        - containerPort: 4369
          name: epmd
        - containerPort: 44053
          name: vmq
        - containerPort: 9100
        - containerPort: 9101
        - containerPort: 9102
        - containerPort: 9103
        - containerPort: 9104
        - containerPort: 9105
        - containerPort: 9106
        - containerPort: 9107
        - containerPort: 9108
        - containerPort: 9109
        env:
        - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
          value: "1"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DOCKER_VERNEMQ_KUBERNETES_APP_LABEL
          value: "vernemq"
        - name: DOCKER_VERNEMQ_KUBERNETES_CLUSTER_NAME
          value: "vernemq"  
        - name: DOCKER_VERNEMQ_KUBERNETES_NAMESPACE
          value: "iot"
        - name: DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MINIMUM
          value: "9100"
        - name: DOCKER_VERNEMQ_ERLANG__DISTRIBUTION__PORT_RANGE__MAXIMUM
          value: "9109"
        volumeMounts:
          - name: vernemq-config-volume
            mountPath: /etc/vernemq/vernemq.conf
            subPath: vernemq.conf
          - name: vernemq-acl-volume
            mountPath: /etc/vernemq/vmq.acl
            subPath: vmq.acl
        resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 256Mi
      volumes:
      - name: vernemq-config-volume
        configMap:
          name: vernemq-config
      - name: vernemq-acl-volume
        configMap:
          name: vernemq-acl
```

Also noticing that, when the NS is "default", the broker starts up
`2018-11-05 21:31:42.820 [info] <0.31.0> Application plumtree started on node 'VerneMQ@vernemq-0.null.default.svc.cluster.local'
2018-11-05 21:31:44.509 [info] <0.31.0> Application vmq_plugin started on node 'VerneMQ@vernemq-0.null.default.svc.cluster.local'
2018-11-05 21:31:44.509 [info] <0.31.0> Application ssl_verify_fun started on node 'VerneMQ@vernemq-0.null.default.svc.cluster.local'
2018-11-05 21:31:44.509 [info] <0.31.0> Application epgsql started on node 'VerneMQ@vernemq-0.null.default.svc.cluster.local'
2018-11-05 21:31:50.110 [info] <0.31.0> Application hackney started on node 'VerneMQ@vernemq-0.null.default.svc.cluster.local'
2018-11-05 21:32:17.113 [info] <0.327.0>@vmq_reg_trie:handle_info:183 loaded 0 subscriptions into vmq_reg_trie
2018-11-05 21:32:19.819 [info] <0.222.0>@vmq_cluster:init:114 plumtree peer service event handler 'vmq_cluster' registered
2018-11-05 21:32:41.311 [info] <0.31.0> Application vmq_acl started on node 'VerneMQ@vernemq-0.null.default.svc.cluster.local'
2018-11-05 21:32:43.853 [info] <0.31.0> Application vmq_passwd started on node 'VerneMQ@vernemq-0.null.default.svc.cluster.local'
2018-11-05 21:32:52.907 [info] <0.31.0> Application vmq_server started on node 'VerneMQ@vernemq-0.null.default.svc.cluster.local'`

but when the NS is injected through an environment variable 
`- name: DOCKER_VERNEMQ_KUBERNETES_NAMESPACE
           value: "test"`
the logs alternative successful connection and then termination due to remote node not being available.
