### ISSUE TITLE
Helm Chart: Need a way to configure additional service/container ports

### ISSUE THREAD

**Issue by JohnCMcDonough** [vernemq/docker-vernemq#99]
The Service field in the helm chart currently only has the `type` field, which allows you to set `NodePort`, `ClusterIP`, or `LoadBalancer`. You are unable to set the `nodePort` and the `port` the service listens on. 

It would be easy to add these as extra fields on the service field, without breaking compatibility.

**values.yaml**
``` yaml
service:
 # NodePort - Listen to a port on nodes and forward to the service.
 # ClusterIP - Listen on the service internal to the cluster only.
 # LoadBalancer - Create a LoadBalancer in the cloud provider and forward to the service.
  type: NodePort
  # This is the port used by nodes to expose the service
  nodePort: 31883
  # Port used when connecting to the service internal to the cluster or externally with a load balancer
  # port: 1883
```
**service.yaml**
``` yaml
    - port: {{ default 1883 .Values.service.port }}
      name: mqtt
      {{ if .Values.service.nodePort }} 
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
```

Additionally, there is only one port configured on the service, TCP MQTT. We should also add support for WebSocket, and maybe HTTP. I'm not sure if these are things we want to add to the Helm Chart, or require them to be deployed as separate services.

I'm also not sure how to make this change without breaking compatibility with previous versions of the helm chart.

@francois-travais any input on this issue?
